/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoldSlugRouteImport } from './routes/sold.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldSlugRoute = SoldSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SoldRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/listings/$slug': typeof ListingsSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/listings/$slug': typeof ListingsSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/listings/$slug': typeof ListingsSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
    | '/sold/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
    | '/sold/$slug'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
    | '/sold/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  SoldRoute: typeof SoldRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold/$slug': {
      id: '/sold/$slug'
      path: '/$slug'
      fullPath: '/sold/$slug'
      preLoaderRoute: typeof SoldSlugRouteImport
      parentRoute: typeof SoldRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
  }
}

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface SoldRouteChildren {
  SoldSlugRoute: typeof SoldSlugRoute
}

const SoldRouteChildren: SoldRouteChildren = {
  SoldSlugRoute: SoldSlugRoute,
}

const SoldRouteWithChildren = SoldRoute._addFileChildren(SoldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ListingsRoute: ListingsRouteWithChildren,
  SoldRoute: SoldRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
