/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SoldSlugRouteImport } from './routes/sold.$slug'
import { Route as PreviewSlugRouteImport } from './routes/preview.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as AdminRealtorsRouteImport } from './routes/admin.realtors'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminImportListingRouteImport } from './routes/admin.import-listing'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldSlugRoute = SoldSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SoldRoute,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)
const AdminRealtorsRoute = AdminRealtorsRouteImport.update({
  id: '/admin/realtors',
  path: '/admin/realtors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportListingRoute = AdminImportListingRouteImport.update({
  id: '/admin/import-listing',
  path: '/admin/import-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import-listing': typeof AdminImportListingRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import-listing': typeof AdminImportListingRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import-listing': typeof AdminImportListingRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import-listing'
    | '/admin/listings'
    | '/admin/realtors'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import-listing'
    | '/admin/listings'
    | '/admin/realtors'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/listings'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import-listing'
    | '/admin/listings'
    | '/admin/realtors'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  SoldRoute: typeof SoldRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminImportListingRoute: typeof AdminImportListingRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminRealtorsRoute: typeof AdminRealtorsRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold/$slug': {
      id: '/sold/$slug'
      path: '/$slug'
      fullPath: '/sold/$slug'
      preLoaderRoute: typeof SoldSlugRouteImport
      parentRoute: typeof SoldRoute
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/admin/realtors': {
      id: '/admin/realtors'
      path: '/admin/realtors'
      fullPath: '/admin/realtors'
      preLoaderRoute: typeof AdminRealtorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-listing': {
      id: '/admin/import-listing'
      path: '/admin/import-listing'
      fullPath: '/admin/import-listing'
      preLoaderRoute: typeof AdminImportListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface SoldRouteChildren {
  SoldSlugRoute: typeof SoldSlugRoute
}

const SoldRouteChildren: SoldRouteChildren = {
  SoldSlugRoute: SoldSlugRoute,
}

const SoldRouteWithChildren = SoldRoute._addFileChildren(SoldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ListingsRoute: ListingsRouteWithChildren,
  SoldRoute: SoldRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminImportListingRoute: AdminImportListingRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminRealtorsRoute: AdminRealtorsRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
