/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SoldSlugRouteImport } from './routes/sold.$slug'
import { Route as PreviewSlugRouteImport } from './routes/preview.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as AdminRealtorsRouteImport } from './routes/admin.realtors'
import { Route as AdminManualImportRouteImport } from './routes/admin.manual-import'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldSlugRoute = SoldSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SoldRoute,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRealtorsRoute = AdminRealtorsRouteImport.update({
  id: '/admin/realtors',
  path: '/admin/realtors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManualImportRoute = AdminManualImportRouteImport.update({
  id: '/admin/manual-import',
  path: '/admin/manual-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manual-import': typeof AdminManualImportRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manual-import': typeof AdminManualImportRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/listings': typeof ListingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/sold': typeof SoldRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manual-import': typeof AdminManualImportRoute
  '/admin/realtors': typeof AdminRealtorsRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/sold/$slug': typeof SoldSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/listings'
    | '/setup'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/manual-import'
    | '/admin/realtors'
    | '/api/image-proxy'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/listings'
    | '/setup'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/manual-import'
    | '/admin/realtors'
    | '/api/image-proxy'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/listings'
    | '/setup'
    | '/sold'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/manual-import'
    | '/admin/realtors'
    | '/api/image-proxy'
    | '/listings/$slug'
    | '/preview/$slug'
    | '/sold/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SoldRoute: typeof SoldRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManualImportRoute: typeof AdminManualImportRoute
  AdminRealtorsRoute: typeof AdminRealtorsRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold/$slug': {
      id: '/sold/$slug'
      path: '/$slug'
      fullPath: '/sold/$slug'
      preLoaderRoute: typeof SoldSlugRouteImport
      parentRoute: typeof SoldRoute
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/realtors': {
      id: '/admin/realtors'
      path: '/admin/realtors'
      fullPath: '/admin/realtors'
      preLoaderRoute: typeof AdminRealtorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manual-import': {
      id: '/admin/manual-import'
      path: '/admin/manual-import'
      fullPath: '/admin/manual-import'
      preLoaderRoute: typeof AdminManualImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface SoldRouteChildren {
  SoldSlugRoute: typeof SoldSlugRoute
}

const SoldRouteChildren: SoldRouteChildren = {
  SoldSlugRoute: SoldSlugRoute,
}

const SoldRouteWithChildren = SoldRoute._addFileChildren(SoldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ListingsRoute: ListingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SoldRoute: SoldRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminImportRoute: AdminImportRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManualImportRoute: AdminManualImportRoute,
  AdminRealtorsRoute: AdminRealtorsRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
